# Generated by Django 3.1 on 2020-09-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_auto_20200821_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingprovider',
            name='date_joined',
            field=models.DateTimeField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingprovider',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='shippingprovider',
            name='transport_mode',
            field=models.CharField(max_length=30),
        ),
    ]
